# Generated by Django 4.2.5 on 2024-01-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='conf_password',
        ),
    ]
